SELECT
  CAST(ANO AS INTEGER) AS ANO,
  NO_UF,
  CAST(CO_MUNICIPIO AS VARCHAR) AS COD_MUN,
  'CRE' AS ETAPA_ENSINO,
  'Creche' AS ETAPA_ENSINO_NOME,
  'CRE' AS ETAPA_ENSINO_DETALHE,
  'Creche' AS ETAPA_ENSINO_DETALHE_NOME,
  COALESCE(QT_MAT_INF_CRECHE_INT_TOT, 0) AS QT_MAT_INTEGRAL,
  COALESCE(QT_MAT_INF_CRECHE_PAR_TOT, 0) AS QT_MAT_PARCIAL
FROM fujisima_db.marts.tb_educacao_basica_municipio_creche_turno
WHERE ANO = 2025

UNION ALL

SELECT
  CAST(ANO AS INTEGER) AS ANO,
  NO_UF,
  CAST(CO_MUNICIPIO AS VARCHAR) AS COD_MUN,
  'PRE' AS ETAPA_ENSINO,
  'Pre-escola' AS ETAPA_ENSINO_NOME,
  'PRE' AS ETAPA_ENSINO_DETALHE,
  'Pre-escola' AS ETAPA_ENSINO_DETALHE_NOME,
  COALESCE(QT_MAT_INF_PREESCOLA_INT_TOT, 0) AS QT_MAT_INTEGRAL,
  COALESCE(QT_MAT_INF_PREESCOLA_PAR_TOT, 0) AS QT_MAT_PARCIAL
FROM fujisima_db.marts.tb_educacao_basica_municipio_preescola_turno
WHERE ANO = 2025

UNION ALL

SELECT
  CAST(ANO AS INTEGER) AS ANO,
  NO_UF,
  CAST(CO_MUNICIPIO AS VARCHAR) AS COD_MUN,
  'AI' AS ETAPA_ENSINO,
  'Anos iniciais' AS ETAPA_ENSINO_NOME,
  'AI' AS ETAPA_ENSINO_DETALHE,
  'Anos iniciais' AS ETAPA_ENSINO_DETALHE_NOME,
  COALESCE(QT_MAT_FUND_AI_INT_TOT, 0) AS QT_MAT_INTEGRAL,
  COALESCE(QT_MAT_FUND_AI_PAR_TOT, 0) AS QT_MAT_PARCIAL
FROM fujisima_db.marts.tb_educacao_basica_municipio_anosiniciais_turno
WHERE ANO = 2025

UNION ALL

SELECT
  CAST(ANO AS INTEGER) AS ANO,
  NO_UF,
  CAST(CO_MUNICIPIO AS VARCHAR) AS COD_MUN,
  'AF' AS ETAPA_ENSINO,
  'Anos finais' AS ETAPA_ENSINO_NOME,
  'AF' AS ETAPA_ENSINO_DETALHE,
  'Anos finais' AS ETAPA_ENSINO_DETALHE_NOME,
  COALESCE(QT_MAT_FUND_AF_INT_TOT, 0) AS QT_MAT_INTEGRAL,
  COALESCE(QT_MAT_FUND_AF_PAR_TOT, 0) AS QT_MAT_PARCIAL
FROM fujisima_db.marts.tb_educacao_basica_municipio_anosfinais_turno
WHERE ANO = 2025
;
