SELECT
  CAST(ANO AS INTEGER) AS ANO,
  NO_UF,
  CAST(CO_MUNICIPIO AS VARCHAR) AS COD_MUN,
  (
    COALESCE(QT_MAT_EM_PROPEDEUTICO, 0) +
    COALESCE(QT_MAT_EM_NORMALMAGISTERIO, 0) +
    COALESCE(QT_MAT_EM_IFTP_QUALIFICACAO_PROFISSIONAL, 0) -
    COALESCE(QT_MAT_ED_PROFISSIONAL_CURSO_TECNICO_CONCOMITANTE, 0)
  ) AS QT_MAT_EM_PROPEDEUTICO,
  COALESCE(
    QT_MAT_ED_PROFISSIONAL_TECNICA_EM_IFTP_CURSO_TECNICO,
    0
  ) AS QT_MAT_EM_EPT
FROM fujisima_db.marts.tb_educacao_basica_municipio_matricula
WHERE ANO = 2025
;
